name: Issue
labels: ["bug"]
description: "No Description."

body:
  - type: textarea
    id: description
    attributes:
      label: Description
      render: markdown
    validations:
      required: true
  - type: dropdown
    id: priority
    attributes:
      label: Priority
      options:
        - Critical
        - High
        - Medium
        - Low
    validations:
      required: false

  - type: input
    id: module
    attributes:
      label: Affected Module
    validations:
      required: false

  - type: input
    id: package
    attributes:
      label: Affected Package
    validations:
      required: false

  - type: dropdown
    id: status
    attributes:
      label: Status
      options:
        - Not Started
        - Investigating
        - In Progress
        - Blocked
        - Need Help
    validations:
      required: false

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      render: markdown
    validations:
      required: false

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      render: markdown
    validations:
      required: false

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      render: markdown
    validations:
      required: false

  - type: textarea
    id: attempts
    attributes:
      label: Attempts Made
      render: markdown
    validations:
      required: false

  - type: textarea
    id: notes
    attributes:
      label: Additional Notes
      render: markdown
    validations:
      required: false
      
  - type: textarea
    id: logs
    attributes:
      label: Attach Logs
    validations:
      required: false

